### PR TITLE
fix: require check had inverted logical condition

### PR DESCRIPTION
**Pull request by mikelord007**

### CODE REVIEW

**Comment by mikelord007** [comment]
Hey keep3r!

I found a small bug while playing around with rKP3R.sol and I think the logical check for one of the _require_  in redeem function was wrong.

**Comment by stitetsati** [comment]
the original impl is actually correct
for an option to be able to be redeemed
```  require(_opt.expiry >= block.timestamp && !_opt.exercised);```
the expiry has to be larger than current time stamp, meaning it HAS NOT EXPIRED.

**Comment by stitetsati** [comment]
but the refund function indeed has the inverted logical statement that needs to be fixed.

**Comment by mikelord007** [comment]
> the original impl is actually correct for an option to be able to be redeemed ` require(_opt.expiry >= block.timestamp && !_opt.exercised);` the expiry has to be larger than current time stamp, meaning it HAS NOT EXPIRED.

I don't understand, so if the expirty isn't to lock the tokens there until expiration happens, what is it used for?
Does this mean they can redeem the rewards instantly once the options is minted?

**Comment by stitetsati** [comment]
options are only exercisable before they expire. you can read more about what an option is on wikipedia or investopedia

**Pull request closed without merging**
